version: '3'

services:
    nodeapp:
        container_name: to-do-list-be
        image: silvaej/to-do-list-be
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - '8080:8080'
        volumes:
            - .:/usr/src/app
            - ./node_modules:/usr/src/app/node_modules
        environment:
            - NODE_ENV=production
        command: ['npm', 'start']
